version: "3"

services:
  app:
    build: ./0x0
    container_name: flask
    environment:
      DATABASE_URI: "postgresql://toor:toor@db/db"
      FLASK_APP: fhost
      APP_PORT: 8080
    volumes:
      - ./data/up:/app/up
    expose:
      - 8080
    depends_on:
      - db

  db:
    image: postgres
    container_name: postgres
    environment:
      - "POSTGRES_PASSWORD=toor"
      - "POSTGRES_USER=toor"
      - "POSTGRES_DB=db"
    expose:
      - 5432
    volumes:
      - ./data/db:/var/lib/postgresql/data

  nginx:
    build: ./nginx
    container_name: nginx
    volumes:
      - ./data/up:/etc/nginx/html/up
    ports:
      - 80:80
    depends_on:
      - app
