name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the app Docker image
      run: docker build . --file 0x0/Dockerfile --tag 0x0-app:$(date +%s)
    - uses: actions/checkout@v4
    - name: Build the nginx Docker image
      run: docker build . --file nginx/Dockerfile --tag 0x0-nginx:$(date +%s)
