name: Docker Image CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: cd into 0x0 directory and build Docker image
        run: cd 0x0/ && docker build . --tag 0x0-app:$(date +%s)
      - uses: actions/checkout@v4
      - name: cd into nginx directory and build Docker image
        run: cd nginx/ && docker build . --tag 0x0-nginx:$(date +%s)
